include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ---------- PRODUCTION SAFETY RULES ----------
    avoid_print: true
    avoid_empty_else: true
    avoid_returning_null_for_void: true
    avoid_shadowing_type_parameters: true
    avoid_type_to_string: true
    collection_methods_unrelated_type: true
    no_logic_in_create_state: true
    use_key_in_widget_constructors: true
    use_build_context_synchronously: true

    # ---------- PERFORMANCE ----------
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true

    # ---------- MAINTAINABILITY ----------
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    always_declare_return_types: true
    unnecessary_nullable_for_final_variable_declarations: true

    # ---------- CODE CLEANLINESS ----------
    always_use_package_imports: true
    prefer_single_quotes: true
    sort_constructors_first: true
    directives_ordering: true
    unnecessary_null_checks: true

    # ---------- OPTIONAL BUT HIGHLY RECOMMENDED ----------
    omit_local_variable_types: false
